# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 710a637876677710fa4c25c593f4c8104c87235f039e3c90e868d8c306d9ccb1ca8f1c9e8376997165cca9ba66b505a0b61026f0ad5ec1c9b79756f38b08b06f

test:
  secret_key_base: 1f17dc36bd55f27ebd476039f634479f064b99a657d129e1f452fede09e6bb72e1cfc1dde45c57a631737f40cde6bca690d6bb3abd939af41966b6d20b18fab5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
